### ISSUE TITLE
Myo Service Control UUID in MyoDiscoveryAgent should be moved to another library method

### ISSUE THREAD

**Issue by Little-Jon** [urbaneinnovation/node-myo#1]
MyoDiscoveryAgent uses a hard-coded UUID to check for BLE devices which advertise the Myo's Service Control UUID. The UUID should be generated from the bluetooth protocol published by Thalmic instead.

**Comment by ManuelOverdijk** [comment]
@Little-Jon 
Can you elaborate on why the UUID should be generated from the bluetooth protocol? As http://developerblog.myo.com/myo-bluetooth-spec-released/ directly states that the Myo will be sending out d5060001a904deb947482c7f4a124842 as UUID

**Comment by Little-Jon** [comment]
@ManuelOverdijk - I think my phrasing was a bit off here. This was more a reminder that the UUID shouldn't be hardcoded in the myo-discovery-agent module, and should ask another module for that information. I just pushed a commit that addresses this. I don't mind hard-coding the protocol, as long as it's contained.
